### ISSUE TITLE
Ghostery breaks the app

### ISSUE THREAD

**Issue by ear** [andrew/first-pr#14]
Looks like the app assumes twttr will be defined when app.js runs.

[Ghostery](https://www.ghostery.com/en/) prevents it: consequently [`renderData`](https://github.com/andrew/first-pr/blob/gh-pages/app.js#L40) fails.

![debugger](https://cloud.githubusercontent.com/assets/2104122/3080571/78286ba4-e4b2-11e3-841c-a61da9ed623a.png)

**Comment by andrew** [comment]
I've pushed a change that should fix that issue, please reopen if it doesn't.

**Comment by ear** [comment]
Perfect. Thank you!
