### ISSUE TITLE
Convert styles to Scss

### ISSUE THREAD

**Issue by andrew** [andrew/first-pr#17]
Seeing as we've got a build system now, we can make our stylesheet a little nicer to work with by converting it to Sass, ideally using: https://github.com/dlmanning/gulp-sass

_n.b. That means only Sass features up to 3.1 that are supported in libsass._

**Comment by mcmillan** [comment]
Any preference on syntax? Sass vs SCSS?

**Comment by andrew** [comment]
Libsass only supports .scss so that make it an easy choice!

**Comment by mcmillan** [comment]
Facepalm! Is @sturobson having a crack at this?

**Comment by andrew** [comment]
He did mention it on twitter

**Comment by briannelson** [comment]
Oh, you should have just asked me @andrew :)

**Comment by andrew** [comment]
@briannelson it was my lame attempt to get more people involved ;)

**Comment by briannelson** [comment]
No worries, @sturobson is doing a better job than I would have anyways, lol.

**Comment by andrew** [comment]
Fixed by @sturobson in https://github.com/andrew/first-pr/pull/18
