### ISSUE TITLE
Exclude PR to self owned repo

### ISSUE THREAD

**Issue by M-Zuber** [andrew/first-pr#22]
Would you consider a feature (off by default?) that does not look at PR's made to a repo that the user owns?

For example my first 20+ PR's where made to projects I own (and was working on myself, but still using Guthub Flow). It would nice to use this tool and see my first `OSS` PR

**Comment by andrew** [comment]
Perhaps the simplest way to implement this is to have a link to browse all of a users PRs, i.e: https://github.com/search?o=asc&q=is%3Apr+author%3AM-Zuber&ref=searchresults&s=created&type=Issues&utf8=%E2%9C%93

**Comment by M-Zuber** [comment]
This search gives you all the PRs made by me, to repos not owned by me
https://github.com/search?utf8=%E2%9C%93&q=is%3Apr+author%3AM-Zuber+-user%3Am-zuber&type=Issues&ref=searchresults

The important part is `-user:m-zuber`
The question then remains, should [this](https://github.com/andrew/first-pr/blob/gh-pages/js/05.app.js#L21) be updated to include it?
Or on results page should we offer a link that redirects to itself after adding the filter?

**Comment by andrew** [comment]
Yeah that looks good, fancy sending the update app.js as a pull request?
