### ISSUE TITLE
Display more PRs?

### ISSUE THREAD

**Issue by phillipj** [andrew/first-pr#24]
First of all, very cool and small project :+1:

Have you thought about displaying more than the first PR? :) ..I would have loved being able to have more history and really like the design and simplicity of what you have created.

**Comment by andrew** [comment]
@briannelson any thoughts on how we could fit this into the design? Perhaps we could add a link to the [search results](https://github.com/search?o=asc&q=is%3Apr+author%3Aphillipj&ref=searchresults&s=created&type=Issues&utf8=%E2%9C%93) so you can browse all of your previous pull requests?

**Comment by briannelson** [comment]
![first pull request what was the first pull request you sent on github 2015-08-30 21-11-32](https://cloud.githubusercontent.com/assets/29120/9570513/c8183a58-4f5b-11e5-92d8-0eabb2a44d77.jpg)

@andrew what do you think about this?

**Comment by andrew** [comment]
Speedy :ship: by @briannelson!

**Comment by phillipj** [comment]
Nice, thanks guys! :+1:
