### ISSUE TITLE
Displays "doesn't appear to be on GitHub at all" for users who just haven't ever made a PR

### ISSUE THREAD

**Issue by tianon** [andrew/first-pr#32]
The language when a user exists but hasn't ever made a PR is slightly misleading (for example, http://firstpr.me/#torvalds) -- you could argue that they're not really "on" GitHub if they don't use PRs, but it seems like it'd be easier to just update the language to mention that this might be the case. :smile:

I'd be willing to make a PR if it'd be desired, but I'm not going to be terribly hurt if you just close this either -- didn't see anyone really bring up this edge case in any of the issues so I figured I'd file it. :+1:

**Comment by andrew** [comment]
That would be great @tianon, I'd be happy to merge a pull request to improve the messaging there.

**Comment by tianon** [comment]
Oh this is getting closer to strange territory -- went to go test this and verify that my new message isn't going to make the page look hideous and http://firstpr.me/#torvalds now has a different message (`It doesn't look like torvalds has sent a pull request yet.`).  Wonder why it couldn't look him up properly the first time I tried?

**Comment by andrew** [comment]
Looking into the code, it looks like you might have received an error from the GitHub API the first time which caused the error template to be shown: https://github.com/andrew/first-pr/blob/gh-pages/index.html#L117

I wonder if there's a way we can tell the difference between "error loading json" and "isn't a valid github username" to avoid this confusion?
