### ISSUE TITLE
Goes back to 2010 but not before.

### ISSUE THREAD

**Issue by jdalton** [andrew/first-pr#33]
It looks like there's a cap at 2010.

See [savetheclocktower](http://firstpr.me/#savetheclocktower). He's a contributor to Prototype.js which was primarily active from 2005–2008.
I'd expect to see PRs a bit farther back than 2010. I see a similar cap for [me](http://firstpr.me/#jdalton) too.

Could be related to [Pull Requests 2.0](https://github.com/blog/712-pull-requests-2-0).

**Comment by jdalton** [comment]
Could be related to [Pull requests 2.0](https://github.com/blog/712-pull-requests-2-0).

**Comment by andrew** [comment]
Yeah it only works for pull requests 2.0 as there's no way to get data on old 1.0 pull requests.

**Comment by jdalton** [comment]
Is this documented somewhere on first-pr?

**Comment by andrew** [comment]
No, not at the moment, might be worth adding it to the readme
