### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by andrew** [andrew/first-pr#6]
Likely one from Font Awesome: http://fortawesome.github.io/Font-Awesome/icon/code-fork/

![screen shot 2014-05-04 at 11 48 51 pm](https://cloud.githubusercontent.com/assets/1060/2874256/52f12ed2-d3de-11e3-8863-6d8ebd217943.png)

**Comment by briannelson** [comment]
@andrew What about something like this?

![icon](https://cloud.githubusercontent.com/assets/29120/3062943/0f3f2b4a-e22e-11e3-9937-5ae6de7e7c56.png)

**Comment by andrew** [comment]
Yeah that's pretty neat.
