### ISSUE TITLE
Running "yarn install" throws an error

### ISSUE THREAD

**Issue by 1ven** [andrew/first-pr#806]
I'm using node v.8.4.0.
After running `yarn install`, I'm getting this output in the console:
```
[1/5] 🔍  Validating package.json...
error first-pr@1.0.0: The engine "node" is incompatible with this module. Expected version "7.10".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Could that happen because of `.nvmrc` file?

**Comment by andrew** [comment]
@1ven yeah, I just updated the project to run on node 8.7, shouldn't run into that error again now
