### ISSUE TITLE
Custom domain?

### ISSUE THREAD

**Issue by andrew** [andrew/first-pr#9]
I was thinking of purchasing a .com domain for this, maybe `first-pr.com`, any other suggestions?

**Comment by briannelson** [comment]
I like that. What about a .me extension? Or is that lame?

**Comment by andrew** [comment]
Nice and short, I'll register firstpr.me now.

If we had $1000/year first.pr would have been perfect!

**Comment by briannelson** [comment]
Oh DAMN, `first.pr` would be great. Can't GitHub sponsor this or something? :wink:

**Comment by andrew** [comment]
Purchased, just waiting for DNS to propegate and it'll be available on: http://firstpr.me/
