### ISSUE TITLE
Upgrade concat-with-sourcemaps

### ISSUE THREAD

**Issue by andrew** [andrew/first-pr#949]
Libraries.io has found that there is a newer version of concat-with-sourcemaps that this project depends on.

More info: https://libraries.io/npm/concat-with-sourcemaps

**Comment by emilioidk** [comment]
It looks like there's been a couple of releases more since you opened the issue...should the version be upgraded to 1.0.6 or to 1.1.0?

**Comment by andrew** [comment]
Updated the issue to be less specific
