### ISSUE TITLE
Properly handle 403 response from server when requesting Pull request information

### ISSUE THREAD

**Issue by emilioidk** [andrew/first-pr#950]
While searching the user's issues doesn't seem to bring any problems but the second request (to get the pull request information) hangs the app if the response is an error. Particularly I am getting the following answer

```
{
  "message": "API rate limit exceeded for 90.185.197.134. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```
but perhaps any error response could be handled similarly.

**Comment by andrew** [comment]
Agreed, we should handle errors from the github api gracefully
