### ISSUE TITLE
Upgrade buffer-from to version 1.1.0

### ISSUE THREAD

**Issue by andrew** [andrew/first-pr#954]
Libraries.io has found that there is a newer version of buffer-from that this project depends on.

More info: https://libraries.io/npm/buffer-from/1.1.0

**Comment by jrm2k6** [comment]
Quick question: buffer-from is not a direct dependency in package.json, right? So how would you go about updating that version? I see this package referenced only in the yarn.lock file

**Comment by andrew** [comment]
Just need to update the yarn.lock file with the yarn update command

**Comment by jrm2k6** [comment]
Oh ok I see. I am not super familiar with yarn but after trying:
`yarn upgrade buffer-from` -> no dependencies updated
`yarn upgrade buffer-from@1.1.0` -> add buffer-from as a dependency in package.json
`yarn upgrade` -> upgrade buffer-from to right version but will also upgrade all the other packages, which doesn't seem to be what we want.

Should I just go ahead with a regular yarn upgrade?

**Comment by andrew** [comment]
Yeah regular update is good 👍
