### ISSUE TITLE
Error when trying to submit Github handle

### ISSUE THREAD

**Issue by jrm2k6** [andrew/first-pr#955]
When submitting github handle:

<img width="1263" alt="screen shot 2018-06-18 at 7 17 25 pm" src="https://user-images.githubusercontent.com/1088099/41572408-6f475ace-732c-11e8-9b2c-361dd06a8448.png">

**Comment by andrew** [comment]
Oh that's weird, can you provide more details about the browser you're using?

**Comment by jrm2k6** [comment]
Using Chrome 67, up to date.
 When I enter my github handle and press enter it redirects to https://firstpr.me/?login=jrm2k6

**Comment by andrew** [comment]
Ah it looks like a https content warning, investigating now

**Comment by andrew** [comment]
@jrm2k6 I've just pushed an update that should fix it, can you confirm its working for you? https://firstpr.me/#jrm2k6

**Comment by jrm2k6** [comment]
@andrew yep it looks good now.
Thanks!

**Comment by andrew** [comment]
👍
