### ISSUE TITLE
Can't get information from GitHub

### ISSUE THREAD

**Issue by politician** [andrew/first-pr#957]
If I type "andrew" for example, I get an error as shown in the screenshot below
<img width="1454" alt="screenshot 2018-10-17 at 17 04 11" src="https://user-images.githubusercontent.com/3155568/47119014-f117d680-d22e-11e8-8617-3d771d89419e.png">

**Comment by andrew** [comment]
Are you loading the site over https? 
https://firstpr.me/#Andrew

**Comment by politician** [comment]
I am not sure if I was or not. Now when I try on both http and https, it's working. Maybe a temporary error?

**Comment by andrew** [comment]
Could have been a temporary rate limit error perhaps, please reopen if it happens again
